spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: zdp1985@0829ZDP
mybatis:
  config-location: classpath:mybatis/mybatis.xml # 设置配置路径位置
  mapper-locations: classpath:mybatis/mapper/*.xml # 设置mapper路径位置
server:
  port: 8080