spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?useSSL=false&characterEncoding=utf-8&useLegacyDatetimeCode=true
    username: root
    password: zdp1985@0829ZDP
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 配置mapper.xml和mybatis-config.xml的路径
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml