spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?useSSL=false&characterEncoding=utf-8&useLegacyDatetimeCode=true
    username: root
    password: zdp19850829
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8