server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: zdp1985@0829ZDP

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 这个配置会将执行的sql打印处理，在开发或测试的时候可以用
    map-underscore-to-camel-case: true # 是否启用驼峰命名
  global-config:
    db-config: # mybatis-plus逻辑删除相关配置与@TableLogic配合达到逻辑删除的目的
      logic-not-delete-value: 0 # 逻辑未删除字段值（默认为0）
      logic-delete-value: 1 # 逻辑已删除字段值（默认为1）

# 日志输出
logging:
  level:
    com.robinzhu.mybatis_plus.entity: trace