server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis?useSSL=false&characterEncoding=utf-8&useLegacyDatetimeCode=true&allowPublicKeyRetrieval=true
    username: root
    password: zdp1985@0829ZDP
mybatis:
  type-aliases-package: com.robinzhu.mybatis.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    com:
      robinzhu:
        mybatis_xml:
          entity: trace