server:
  port: 8888
  servlet:
    context-path: /charter2
blog:
  address: https://www.baidu.com
  author: robin.li
  desc: ${blog.author}, ${blog.address}
  value: ${random.value} # 随机字符串
  number: ${random.int} # 随机整数
  bigNumber: ${random.long} # 随机双精度数
  test1: ${random.int(10)} # 10以内的随机整数
  test2: ${random.int[1, 20]} # 1-20的随机整数
  uuid: ${random.uuid}} # uuid